<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Invoice - {{ $return->bill_no }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #333;
        }

        .invoice-box {
            width: 100%;
            padding: 20px;
            border: 1px solid #ddd;
        }

        h2, h3 {
            margin: 0;
            padding: 0;
        }

        .heading {
            background: #f0f0f0;
            padding: 8px;
            margin-top: 20px;
            font-weight: bold;
            border: 1px solid #ddd;
        }

        .details-table, .items-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        .details-table td {
            padding: 6px;
        }

        .items-table th {
            background: #f0f0f0;
            padding: 8px;
            border: 1px solid #ddd;
            text-align: center;
        }

        .items-table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }

        .total-box {
            margin-top: 20px;
            text-align: right;
            font-size: 14px;
            font-weight: bold;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 11px;
            color: #666;
        }
    </style>
</head>

<body>

<div class="invoice-box">

    <!-- TITLE -->
    <h2 style="text-align:center; margin-bottom:5px;">SCHOOL Management System</h2>
    <p style="text-align:center; margin-top:0; font-size:11px;">School Address, City, State, ZIP</p>

    <hr>

    <!-- INVOICE HEADING -->
    <h3 class="heading">Return Invoice Details</h3>

    <!-- CUSTOMER + INVOICE DETAILS -->
    <table class="details-table">
        <tr>
            <td><strong>Bill No:</strong> {{ $return->bill_no }}</td>
            <td><strong>Date:</strong> {{ $return->created_at->format('d M Y') }}</td>
        </tr>
        <tr>
            <td><strong>Customer:</strong> {{ $return->saleBill->parent->user->name }}</td>
            <td><strong>Payment Mode:</strong> {{ ucfirst($return->saleBill->payment_mode) }}</td>
        </tr>
        <tr>
            <td><strong>Generated By:</strong> {{ $return->return_by->name }}</td>
        </tr>
    </table>

    <!-- ITEMS TABLE -->
    <h3 class="heading">Returned Items</h3>

    <table class="items-table">
        <thead>
            <tr>
                <th>Item</th>
                <th>Variant</th>
                <th>Unit Price (Rs)</th>
                <th>Returned Qty</th>
                <th>Total (Rs)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($return->returnChildren as $child)
            <tr>
                <td>{{ $child->item->name ?? 'N/A' }}</td>
                <td>{{ strtoupper($child->variant) }}</td>
                <td>₹ {{ number_format($child->unit_price, 2) }}</td>
                <td>{{ $child->qty }}</td>
                <td>₹ {{ number_format($child->subtotal, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <!-- TOTAL -->
    <div class="total-box">
        Grand Total: Rs. {{ number_format($return->total_refund, 2) }}
    </div>

    <!-- FOOTER -->
    <div class="footer">
        Return within 24 hours of Sale!<br>
        This is a computer-generated invoice; no signature required.
    </div>

</div>

</body>
</html>
